language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"
# command to install dependencies
install:
  - pip install -e .
  - pip install pytest-cov
  - pip install "python-coveralls"
  - pip uninstall nationstates requests xmltodict ezurl --yes
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-pep8
# command to run tests
script:
  - py.test --cov=nationstates tests/
after_success:
  - coveralls

